version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./secrets:/app/secrets
      - ./data:/app/data
    environment:
      - PORT=${PORT:-3000}
    restart: unless-stopped
